name: NexureJS Tests

on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci
        env:
          # Install without native modules for CI
          NEXUREJS_CI_MODE: 1

      - name: Build TypeScript
        run: npm run build:ts
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Build and test
        run: npm run ci:test
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: ./coverage
